### ISSUE TITLE
Run test that provissioner is sshonly failed 

### ISSUE THREAD

**Issue by xiaohanjie** [datastax/fallout#9]
fallout build is lastest.

My YAML:
---
ensemble:
       server:
              node.count: 1
              provisioner:
                      name:  sshonly
                      properties:
                          host: 10.4.116.46
                          user.name: root
                          user.password: Root123
              configuration_manager:
                      - name: noop
         client: server
workload:
    phases:
       - noop:
                module: sleep
                properties:
                     duration: 1s
    checkers:
        nofail:
             checker: nofail

Run the test. Stat is Failed(SETTING_UP)
Check fallout-errors.log
![714089e6f8722d2ff6be1e26683c834](https://user-images.githubusercontent.com/73681051/147204294-6a2b494e-fed3-446e-9775-8f40ccefb60e.png)
I have a existed_k8s cluster and run a cassandra perfermance test and dtest on it. Could you have  example test yaml file  for cassandra using Dtest? Thanks!

**Comment by kijanowski** [comment]
I think you need to set the `user.name` property at the `server` level. Could you try with this yaml?
```
ensemble:
  server:
    user.name: root
    node.count: 1
    provisioner:
      name: sshonly
      properties:
        host: 10.4.116.46
        user.password: Root123
    configuration_manager:
      - name: noop

  client: server
workload:
  phases:
    - noop:
      module: sleep
      properties:
        duration: 1s
  checkers:
    nofail:
      checker: nofail
```
